sonar.projectKey=RobertoDanielRodriguezLopez_ci-cd-python-project
sonar.organization=robertodanielrodriguezlopez

sonar.projectName=ci-cd-python-project
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml