name: Continuous Integration


on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  tests:
    name: Run tests (unit + API)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ci-python-app .

      - name: Run pytest inside container
        run: |
          docker run --rm ci-python-app pytest
