name: Security Checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bandit (SAST)
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            python:3.11-slim \
            sh -c "pip install bandit && bandit -r /src/app"

      - name: Run Dependency Scan (pip-audit)
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            python:3.11-slim \
            sh -c "pip install pip-audit && pip-audit -r /src/requirements.txt"
